services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_dev
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_esgi_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_ui_dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  app:
    container_name: my-app_dev
    build:
      context: .
      dockerfile: "./docker/dev/Dockerfile"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=mydatabase
      - DB_PASSWORD=admin
      - DB_USER=admin
      - DB_SYNCHRONISE=true
      - DB_HOST=postgres
    depends_on:
      - postgres

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    environment:
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
      - "7181:3000"
    volumes:
      - grafana_volume:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
      - ./grafana/structure.yaml:/etc/grafana/provisioning/dashboards/main.yaml
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  loki:
    image: grafana/loki:latest
    container_name: app_loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./logs:/var/log
      - ./loki/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yml
volumes:
  postgres_esgi_data:
  prometheus:
  grafana_volume:
